apiVersion: v1
kind: Service
metadata:
  name: {{ include "trivia.fullname" . }}
  labels:
    {{- include "trivia.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.backend_port }}
      targetPort: http-backend
      protocol: TCP
      name: http-backend
    - port: {{ .Values.service.frontend_port }}
      targetPort: http-frontend
      protocol: TCP
      name: http-frontend
  selector:
    {{- include "trivia.selectorLabels" . | nindent 4 }}
